"""empty message

Revision ID: 0bfa3083460a
Revises: d62cfe4549fc
Create Date: 2022-06-02 13:53:19.713350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bfa3083460a'
down_revision = 'd62cfe4549fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    op.drop_table('venue')
    op.drop_table('artist')

    op.create_table('Artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('genres', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('seeking_venue', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('genres', sa.String(length=120), nullable=True),
    sa.Column('seeking_talent', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    op.drop_table('Venue')
    op.drop_table('Artist')
    
    op.create_table('artist',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('genres', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('image_link', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('facebook_link', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('website', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('seeking_venue', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('seeking_description', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('show',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('venue_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('artist_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='show_ibfk_1'),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name='show_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('venue',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('image_link', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('facebook_link', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('website', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('genres', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('seeking_talent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('seeking_description', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
